name: CI

on:
  workflow_dispatch: {}

jobs:
  build:
    name: Build and test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: |
            2.1.x
            3.1.x
            5.0.x
            6.0.x
            7.0.404
            8.0.x

      - name: Build Release
        run: dotnet build src -c Release

      - name: Run tests
        run: dotnet test --no-build -f net461

      - name: Pack
        run: dotnet pack src/Transloadit -c Release --no-build --output nuget
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: nuget
          path: nuget/
