name: NuGet Deploy

on:
  workflow_dispatch:
    inputs:
      notifyUrl:
        description: 'Notify url like https://webhook.site'
        required: true
        type: string

concurrency:
  group: deploy-${{ github.repository }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  tests:
    name: Run Tests
    uses: ./.github/workflows/tests.yml
    with:
      notifyUrl: ${{ inputs.notifyUrl }}
    secrets: inherit

  build-package:
    name: Build and Package
    environment: Release
    runs-on: ubuntu-latest
    needs: [tests]

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: 10.0.x

      - name: Build Release
        run: dotnet build src/Transloadit/Transloadit.csproj -c Release

      - name: Pack
        run: dotnet pack src/Transloadit -c Release --no-build --output nuget

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuget
          path: nuget/

  tag:
    name: Add Release Tag
    needs: [build-package]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get Assembly Version
        id: get_version
        run: |
          VERSION=$(sed -n 's/.*<Version>\(.*\)<\/Version>.*/\1/p' src/Transloadit/Transloadit.csproj)
          echo "version=v$VERSION" >> "$GITHUB_OUTPUT"

      - name: Add Current Version Tag
        uses: cardinalby/git-tag-action@v1.0
        env:
          TAG: ${{ steps.get_version.outputs.version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
  publish:
    name: Publish
    needs: [tag]
    runs-on: ubuntu-latest
    steps:
      - name: Download NuGet Artifacts
        uses: actions/download-artifact@v4
        with:
          name: nuget
          path: nuget
      - name: Setup .NET
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: 8.0.x
      - name: Publish NuGet packages to NuGet
        run: dotnet nuget push nuget/*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source "nuget.org"